// This file contains seed data that will be added to the database on first load
// You can use this data to test the application

export const seedItems = [
  {
    title: 'Canon EOS R5 Camera',
    description: 'Professional mirrorless camera with 45MP sensor. Perfect for photography and videography projects.',
    price: 75,
    priceUnit: 'day',
    category: 'Photography',
    location: 'Los Angeles, CA',
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=600&fit=crop',
  },
  {
    title: 'Mountain Bike - Trek X-Caliber',
    description: 'High-performance mountain bike suitable for trails and rough terrain. Well-maintained and ready to ride.',
    price: 35,
    priceUnit: 'day',
    category: 'Sports',
    location: 'Portland, OR',
    imageUrl: 'https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=800&h=600&fit=crop',
  },
  {
    title: 'Portable Generator 5000W',
    description: 'Reliable portable generator for outdoor events, camping, or emergency backup power.',
    price: 50,
    priceUnit: 'day',
    category: 'Tools',
    location: 'Austin, TX',
    imageUrl: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&h=600&fit=crop',
  },
  {
    title: 'DJI Mavic Air 2 Drone',
    description: 'Professional drone with 4K camera and 34-minute flight time. Great for aerial photography.',
    price: 60,
    priceUnit: 'day',
    category: 'Photography',
    location: 'Seattle, WA',
    imageUrl: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&h=600&fit=crop',
  },
  {
    title: 'Camping Tent - 6 Person',
    description: 'Spacious family tent with easy setup. Includes rain fly and storage pockets.',
    price: 25,
    priceUnit: 'day',
    category: 'Outdoor',
    location: 'Denver, CO',
    imageUrl: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800&h=600&fit=crop',
  },
  {
    title: 'Power Drill Set - DeWalt',
    description: 'Complete power drill set with various bits and accessories. Perfect for home projects.',
    price: 20,
    priceUnit: 'day',
    category: 'Tools',
    location: 'Chicago, IL',
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&h=600&fit=crop',
  },
  {
    title: 'Kayak - Single Person',
    description: 'Stable and easy-to-paddle kayak. Includes paddle and life jacket.',
    price: 40,
    priceUnit: 'day',
    category: 'Water Sports',
    location: 'Miami, FL',
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop',
  },
  {
    title: 'Party Speaker System',
    description: 'High-quality speaker system with Bluetooth connectivity. Perfect for parties and events.',
    price: 45,
    priceUnit: 'day',
    category: 'Electronics',
    location: 'New York, NY',
    imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&h=600&fit=crop',
  },
];
